### ISSUE TITLE
Duplicate 3ds games marked as Wii u games in console rpc

### ISSUE THREAD

**Issue by SecretGuy12** [dead8309/Kizzy#143]
For example, go to console RPC, search a Wii u game like mario kart 8 & you'll see it doesn't show anything other than 8 deluxe, but if you search mario kart 7, there will be 2 mario kart 7's, one marked as 3ds and one marked as Wii U.

**Comment by dead8309** [comment]
> but if you search mario kart 7, there will be 2 mario kart 7's, one marked as 3ds and one marked as Wii U.

I think that's because they are available on both Wii u and Nintendo 3ds, also i don't have any data for games you can checkout 

https://github.com/ninstar/Rich-Presence-U-DB for Nintendo,wii u and 3ds games

And https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord for Xbox games 

and make a issue there about duplicate games
